Fix light DOM children stamping to shadow DOM
TimvdLippe/iron-lazy-pages pull request #33
Opened 2016-10-01 12:48 UTC by seaneking

Stamps template to its parent, rather than as child of iron-lazy-pages.

2016-10-01 12:50 UTC, TimvdLippe requested changes
Could you also add a test for this to prevent regressions?

2016-10-01 12:50 UTC, TimvdLippe commented on iron-lazy-pages-behavior.html
> -    }.bind(this), this);
This is still required for https://github.com/TimvdLippe/iron-lazy-pages/pull/33/files#diff-06d57999e47ac40b3528de00729543c9R45

2016-10-01 13:19 UTC, seaneking commented on iron-lazy-pages-behavior.html
> -    }.bind(this), this);
Ah, whoops. Tests didn't catch it.

2016-10-01 13:20 UTC, TimvdLippe commented on iron-lazy-pages-behavior.html
> -    }.bind(this), this);
Yeah I just realized. Will have to make a regression test for that later

2016-10-01 13:20 UTC, seaneking commented
Sure thing. Will try get to it tomorrow.

2016-10-02 00:13 UTC, seaneking commented
Okay so shadow DOM wasn't actually enabled for the second test suite (it's `?dom=shadow`, not `?shadow=1`) and when I enabled it there were heaps of failing tests. Should be all fixed now.

2016-10-02 09:37 UTC, TimvdLippe commented
Thanks for exposing that error! I will take a look later to fix the tests, since some tests are now not testing what they are supposed to.

2016-10-02 10:21 UTC, seaneking commented
Yeah sorry I didn't have time to go over them properly.

Also just pushed another quick change - `self.parentNode` should be protected by `Polymer.dom()` for shady.

Commit history in this PR has become a bit of a mess, sorry. Happy to rebase it after you're satisfied w/ tests.

2016-10-02 10:23 UTC, TimvdLippe commented
If you enabled the option for maintainers to modify your branch, I will fix and squash myself :)

2016-10-02 12:09 UTC, TimvdLippe commented
I have manually merged this PR with the fixed tests. The demo should be working properly now :smile: Thanks a lot for your debugging effort!

2016-10-02 12:09 UTC, closed without merging